// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06nWCElTqsCT6G7EVj2Gzu7-waZ9jsqw',
    appId: '1:43827701403:web:e1ff251e2abb0c2a0f083e',
    messagingSenderId: '43827701403',
    projectId: 'rekoro-57cb2',
    authDomain: 'rekoro-57cb2.firebaseapp.com',
    storageBucket: 'rekoro-57cb2.firebasestorage.app',
    measurementId: 'G-B93WSMM4D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPA5HAOVlFOjXgap4sgOwQe8e8IKgL77Y',
    appId: '1:43827701403:android:b2698bfe640cca6a0f083e',
    messagingSenderId: '43827701403',
    projectId: 'rekoro-57cb2',
    storageBucket: 'rekoro-57cb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtzSR3diqv_AnlYppozkKVGygIyReFFM',
    appId: '1:909413460105:ios:81f965c46905c03380fe58',
    messagingSenderId: '909413460105',
    projectId: 'last-watched-tracker',
    storageBucket: 'last-watched-tracker.firebasestorage.app',
    iosBundleId: 'com.lastWatchedTracker',
  );
}