// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhrFv6_lGL7wuAz-dDj6Zx8Z4QvSSjBlk',
    appId: '1:909413460105:web:872439d5f14b587b80fe58',
    messagingSenderId: '909413460105',
    projectId: 'last-watched-tracker',
    authDomain: 'last-watched-tracker.firebaseapp.com',
    storageBucket: 'last-watched-tracker.firebasestorage.app',
    measurementId: 'G-QV3CJED9Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfWvN9xUt1FjojQv7OJImhFQ5f6L7BXM',
    appId: '1:909413460105:android:8e2c9cb58829c84780fe58',
    messagingSenderId: '909413460105',
    projectId: 'last-watched-tracker',
    storageBucket: 'last-watched-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtzSR3diqv_AnlYppozkKVGygIyReFFM',
    appId: '1:909413460105:ios:81f965c46905c03380fe58',
    messagingSenderId: '909413460105',
    projectId: 'last-watched-tracker',
    storageBucket: 'last-watched-tracker.firebasestorage.app',
    iosBundleId: 'com.lastWatchedTracker',
  );
}
